"""tables

Revision ID: 9e01e9f1d106
Revises: 5add4b571bb6
Create Date: 2022-10-12 14:25:02.739752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e01e9f1d106'
down_revision = '5add4b571bb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_table('genre',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=60), nullable=False),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.create_table('book',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('year', sa.Date(), nullable=False),
    sa.Column('language', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('status', sa.Enum('available', 'pending', name='bookstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('id_genre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_genre'], ['genre.genre_id'], ),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('book_has_authors',
    sa.Column('id_book', sa.Integer(), nullable=False),
    sa.Column('id_author', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_author'], ['author.author_id'], ),
    sa.ForeignKeyConstraint(['id_book'], ['book.book_id'], ),
    sa.PrimaryKeyConstraint('id_book', 'id_author')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('id_book', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_book'], ['book.book_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('book_has_authors')
    op.drop_table('book')
    op.drop_table('genre')
    op.drop_table('author')
    # ### end Alembic commands ###
